# Which is the first triangle number to have over five-hundred divisors?

# Posit: the nth triangle number can be generated by the following equation
def tri(n):
    a = (n+1)/2
    b = n | 1
    return a*b

from math import sqrt

def factor(x):
    sq = sqrt(x)
    sqi = int(sq)
    for i in range(1,sqi+1):
        if (x % i == 0):
            yield i
            top = x/i
            if (i != top):
                yield top

def numFactors(x):
    num = 0
    for i in factor(x):
        num += 1
    return num

import time

start_time = time.time()
i = 1
triNum = 1
while (numFactors(triNum) <= 500):
    i += 1
    triNum += i
stop_time = time.time()

print triNum
print "Calculation took", stop_time - start_time, "seconds."
